config/routes.rb
Rails.application.routes.draw do
  get '/admin', to: 'admin/users#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, only: [:show]
  resources :posts
  root 'posts#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :software_name, presence: true, length: { maximum: 20 }
    validates :content, presence: true, length: { maximum: 1000 }
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :timeoutable, :omniauthable, omniauth_providers: [:twitter]

  has_many :posts

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
      end
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
    def twitter
        @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))
        if @user.persisted?
            sign_in_and_redirect @user
        else
            session["devise.user_attributes"] = @user.attributes
            redirect_to new_user_registration_url
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  PER = 10
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def index
    @posts = Post.all.order(updated_at: :desc).page(params[:page]).per(PER)
  end

  def show
  end

  def new
    unless current_user.username
      redirect_to edit_user_registration_path, notice: "名前を設定してください"
    else
      @post = Post.new
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: "レビューを投稿しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "レビューを編集しました"
    else
      render :edit
    end
  end
  
  def destroy
    if @post.destroy
      redirect_to posts_path, notice: "レビューを削除しました"
    else
      render :index
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:software_name, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  PER = 10
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id]).page(params[:page]).per(PER)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoundsGood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <div class="title_bar">
          <h1 class="logo">SoundsGood</h1>
          <div class="link">
            <% if user_signed_in? %>
              <strong><%= link_to 'マイページ', user_path(current_user.id) %></strong>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to 'サインアップ', new_user_registration_path %>
              <%= link_to 'ログイン', new_user_session_path %>
            <% end %>
            <%= link_to 'レビューを見る', posts_path %>
          </div>
        </div>
      </header>

      <div class="content">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <div class="mainarea">

          <%= yield %>

        </div>

      </div>

      <footer>&copy 2020 CaibeR</footer>

    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |form| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
            <h2><%= @post.errors.count %>件のエラーがあります。</h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
         </div>
    <% end %>
    <div class="software_name">
        <%= form.label :software_name %>
        <%= form.text_field :software_name, maxlength: "20", placeholder: "20文字以内", size: "50" %>
    </div>
    <div class="form_content">
        <%= form.label :content %><br>
        <%= form.text_area :content, maxlength: "1000", placeholder: "1000文字以内", size: "50x10" %>
    </div>
    <%= form.submit "登録" %>
<% end %>
<%= link_to '一覧に戻る', posts_path %>

app/views/posts/edit.html.erb
<h2>レビュー詳細</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<h2>レビュー一覧</h2>
<% if user_signed_in? %>
    <%= link_to 'レビュー投稿', new_post_path %>
<% end %>

<% @posts.each do |post| %>
    <div class="post">
        <p>
            <span class="software_name"><%= post.software_name %></span>
            <span class="written_by">
                <%= post.user.username %>
            </span>
            <%= link_to 'ユーザー詳細', user_path(post.user.id) %>
        </p>
        <p class="index_content">
            <%= post.content %>
        </p>
    </div>
    <p>
        <% if user_signed_in? %>
            <div class="menu">
                <% if current_user.id == post.user.id %>
                    <%= link_to '詳細', post_path(post.id) %>
                <% end %>
            </div>
        <% end %>
    </p>
<% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h2>レビュー投稿</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h2>レビュー詳細</h2>
<div class="post">
    <p>
        <span class="software_name"><%= @post.software_name %></span>
        <span class="written_by">
            <%= @post.user.username %>
        </span>
        <%= link_to 'ユーザー詳細', user_path(@post.user.id) %>
    </p>
    <p class="padding">
        <span class="index_content">
            <%= @post.content %>
        </span>
    </p>
</div>
<% if user_signed_in? %>
    <div class="menu">
        <% if current_user.id == @post.user.id %>
            <%= link_to '編集', edit_post_path(@post.id) %>
            <%= link_to '削除', post_path(@post.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
        <% end %>
    </div>
<% end %>
<%= link_to '一覧へ戻る', posts_path %>

app/views/users/show.html.erb
<% if @user.username %>
    <h1><%= @user.username %>のプロフィール</h1>
<% else %>
    <h1>User<%= @user.id %>のプロフィール</h1>
<% end %>
<h3>ユーザー名</h3>
<p>
    <% if @user.username %>
        <%= @user.username %>
    <% else %>
        User<%= @user.id %>(未設定)
    <% end %>
</p>

<% @posts.each do |post| %>
    <div class="post">
        <p>
            <span class="software_name"><%= post.software_name %></span>
            <span class="written_by">
                <%= post.user.username %>
            </span>
            <%= link_to 'ユーザー詳細', user_path(post.user.id) %>
        </p>
        <p class="padding">
            <span class="index_content">
                <%= post.content %>
            </span>
        </p>
    </div>
    <p>
        <% if user_signed_in? %>
            <div class="menu">
                <% if current_user.id == post.user.id %>
                    <%= link_to '詳細', post_path(post.id) %>
                <% end %>
            </div>
        <% end %>
    </p>
<% end %>

<%= paginate @posts %><br>

<% if @user.id == current_user.id %>
    <%= link_to 'ユーザー情報変更', edit_user_registration_path %>
<% end %>
<%= link_to '一覧へ戻る', posts_path %>